id: A2C285188
title: 'Great Drum of the Devas: A Prayer to the Dharma King Tri Songdetsen'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:49:49.302682
  last_modified_at: 2022-03-01 01:49:49.302689
